language: python
python:
  - "3.6.3"

install:
  - pip install coverage
  - pip install pytest

script:
  - pytest TestTicTacToe.py --cov
  - pytest TestGuessNumber.py --cov

after_success:
  - bash < (curl -s https://codecov.io/bash)
