language: python
python:
  - "3.6.3"

install:
   - pip install codecov

script:
  - coverage run -a TestTicTacToe.py 
  - coverage run -a TestGuessNumber.py

after_success:
  - coveralls
  - codecov --token 3e76ae9f-0096-411b-b8bf-4672b7ed1aef