language: python
python:
  - "3.6.3"

install:
  - pip install coverage
  - pip install pytest

script:
  - pytest TestTicTacToe.py TestGuessNumber.py --cov=codecov

after_success:
  - codecov --token 3e76ae9f-0096-411b-b8bf-4672b7ed1aef
