language: python
python:
  - "3.6.3"

install:
  - pip install codecov
  - pip install pytest

script:
  - coverage run TestTicTacToe.py
  - pytest TestTicTacToe.py --cov
  - pytest TestGuessNumber.py --cov

after_success:
  - codecovst
  - bash < (curl -s https://codecov.io/bash)
