language: python
python:
  - "3.6.3"

# command to install dependencies
install:
  - pip install codecov
  - pip install pytest

script:
  - pytest TestTicTacToe.py
  - coverage run TestTicTacToe.py

after_success:
  - codecovst