language: python
python:
  - "3.6.3"
# command to install dependencies
-install:
  - pip install codecov
  - pip install pytest
-script:
  - pytest TestTicTacToe.py 
  - coverage run TestTicTacToe.py
  - nosetests TestTicTacToe.py -v — with-coverage

after_success:
- bash < (curl -s https://codecov.io/gh/ewwx/ONLINE_GAME)
